---
language: generic
sudo: required
services:
  - docker

env:
  global:
    # Travis still uses trusty
    - DOCKER_VERSION=17.03.1~ce-0~ubuntu-trusty
    - DOCKER_COMPOSE_VERSION=1.13.0
  matrix:
    - OS=jessie64 PLAYBOOK=webhook
    - OS=xenial64 PLAYBOOK=webhook
    - OS=centos7  PLAYBOOK=webhook

before_install:
  - chmod +x ./scripts/install-docker.sh
  - chmod +x ./scripts/ci.sh
  - sudo -E ./scripts/install-docker.sh
install: true
script:
  - make "${OS}" test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
