---
services: docker

env:
  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: centos7
#  - distro: centos6


script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/joshuacherry/481aec647bf62eb05bc97fd8fc725ea2/raw
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure webhook-listener is installed.
  - docker exec $container_id ps -ef | grep webhook-listener

after_success:
  # Clean up.
  - sudo docker rm -f $container_id

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
